//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirbaseAndroidPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdAgencyLog
    {
        public long Id { get; set; }
        public string ServiecName { get; set; }
        public string AddUrl { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
