//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirbaseAndroidPanel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WapPortal_CMSEntities : DbContext
    {
        public WapPortal_CMSEntities()
            : base("name=WapPortal_CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_PortalMaster> tbl_PortalMaster { get; set; }
    
        public virtual ObjectResult<sp_GetContentList_Result> sp_GetContentList(string portalcode, string catcode)
        {
            var portalcodeParameter = portalcode != null ?
                new ObjectParameter("portalcode", portalcode) :
                new ObjectParameter("portalcode", typeof(string));
    
            var catcodeParameter = catcode != null ?
                new ObjectParameter("catcode", catcode) :
                new ObjectParameter("catcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetContentList_Result>("sp_GetContentList", portalcodeParameter, catcodeParameter);
        }
    
        public virtual ObjectResult<sp_getFirbaseBdtubeInfo_Result> sp_getFirbaseBdtubeInfo(string contentcode, string id, string refid)
        {
            var contentcodeParameter = contentcode != null ?
                new ObjectParameter("contentcode", contentcode) :
                new ObjectParameter("contentcode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var refidParameter = refid != null ?
                new ObjectParameter("refid", refid) :
                new ObjectParameter("refid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getFirbaseBdtubeInfo_Result>("sp_getFirbaseBdtubeInfo", contentcodeParameter, idParameter, refidParameter);
        }
    }
}
