//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirbaseAndroidPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PushMessage
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string ImageUrl { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ServiceName { get; set; }
    }
}
