//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirbaseAndroidPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalMaster
    {
        public string PortalCode { get; set; }
        public long PortalID { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string NavigateUrl { get; set; }
        public string HeaderCode { get; set; }
        public string FooterCode { get; set; }
        public string ImageUrl { get; set; }
        public string AlterNetText { get; set; }
        public string PreviewUrl { get; set; }
        public string ParentCode { get; set; }
        public Nullable<int> SortNo { get; set; }
        public int ExtractLevel { get; set; }
        public int DepthLevel { get; set; }
        public string Expired { get; set; }
        public string CSS { get; set; }
        public string ViewType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> IsLoginPage { get; set; }
        public string MainType { get; set; }
    }
}
